### ISSUE TITLE
Registration & Login page(HTML)

### ISSUE THREAD

**Issue by Nym02** [Nym02/SU19CSE299S08G05NSU#4]
Created.

**Comment by Nym02** [comment]
4e5089d3aebf5e929e4e40b279457fd7c9919eaf

**Comment by Nym02** [comment]
a9c42a6c71988c6a5c2cd330833359ebe909c0a6

**Comment by Nym02** [comment]
4d171ca63ecbf447d1c8e9fb7a7d597961d38022

**Comment by abunasib** [comment]
f942bfb8327e617556e15e05de8e4de3c5e76f5a

**Comment by Nym02** [comment]
7a4f09447794a93573984fbe97f770f3eb944cd7

**Comment by Nym02** [comment]
57dc8f771bd868fc10c4d15ce8a683139c05b915
